version: "3.8"
services:
  aws-test-mysql:
    container_name: aws-test-mysql
    image: mysql
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  aws-test-app:
    container_name: aws-test-app01
    image: test-app
    depends_on:
      - aws-test-mysql
    build: .
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    restart: always
